// logo_flash.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module logo_flash (
		input  wire        ufm_clock_clk,          // ufm_clock.clk
		input  wire        ufm_csr_address,        //   ufm_csr.address
		input  wire        ufm_csr_read,           //          .read
		input  wire [31:0] ufm_csr_writedata,      //          .writedata
		input  wire        ufm_csr_write,          //          .write
		output wire [31:0] ufm_csr_readdata,       //          .readdata
		input  wire [12:0] ufm_data_address,       //  ufm_data.address
		input  wire        ufm_data_read,          //          .read
		input  wire [31:0] ufm_data_writedata,     //          .writedata
		input  wire        ufm_data_write,         //          .write
		output wire [31:0] ufm_data_readdata,      //          .readdata
		output wire        ufm_data_waitrequest,   //          .waitrequest
		output wire        ufm_data_readdatavalid, //          .readdatavalid
		input  wire [3:0]  ufm_data_burstcount,    //          .burstcount
		input  wire        ufm_reset_reset_n       // ufm_reset.reset_n
	);

	altera_onchip_flash #(
		.INIT_FILENAME                       ("logo_rom.hex"),
		.INIT_FILENAME_SIM                   ("altera_onchip_flash.dat"),
		.DEVICE_FAMILY                       ("MAX 10"),
		.PART_NAME                           ("10M08SCE144C8G"),
		.DEVICE_ID                           ("08"),
		.SECTOR1_START_ADDR                  (0),
		.SECTOR1_END_ADDR                    (4095),
		.SECTOR2_START_ADDR                  (4096),
		.SECTOR2_END_ADDR                    (8191),
		.SECTOR3_START_ADDR                  (0),
		.SECTOR3_END_ADDR                    (0),
		.SECTOR4_START_ADDR                  (0),
		.SECTOR4_END_ADDR                    (0),
		.SECTOR5_START_ADDR                  (0),
		.SECTOR5_END_ADDR                    (0),
		.MIN_VALID_ADDR                      (0),
		.MAX_VALID_ADDR                      (8191),
		.MIN_UFM_VALID_ADDR                  (0),
		.MAX_UFM_VALID_ADDR                  (8191),
		.SECTOR1_MAP                         (1),
		.SECTOR2_MAP                         (2),
		.SECTOR3_MAP                         (0),
		.SECTOR4_MAP                         (0),
		.SECTOR5_MAP                         (0),
		.ADDR_RANGE1_END_ADDR                (8191),
		.ADDR_RANGE2_END_ADDR                (8191),
		.ADDR_RANGE1_OFFSET                  (512),
		.ADDR_RANGE2_OFFSET                  (0),
		.ADDR_RANGE3_OFFSET                  (0),
		.AVMM_DATA_ADDR_WIDTH                (13),
		.AVMM_DATA_DATA_WIDTH                (32),
		.AVMM_DATA_BURSTCOUNT_WIDTH          (4),
		.SECTOR_READ_PROTECTION_MODE         (28),
		.FLASH_SEQ_READ_DATA_COUNT           (2),
		.FLASH_ADDR_ALIGNMENT_BITS           (1),
		.FLASH_READ_CYCLE_MAX_INDEX          (4),
		.FLASH_RESET_CYCLE_MAX_INDEX         (29),
		.FLASH_BUSY_TIMEOUT_CYCLE_MAX_INDEX  (139),
		.FLASH_ERASE_TIMEOUT_CYCLE_MAX_INDEX (40600000),
		.FLASH_WRITE_TIMEOUT_CYCLE_MAX_INDEX (35380),
		.PARALLEL_MODE                       (1),
		.READ_AND_WRITE_MODE                 (1),
		.WRAPPING_BURST_MODE                 (0),
		.IS_DUAL_BOOT                        ("False"),
		.IS_ERAM_SKIP                        ("True"),
		.IS_COMPRESSED_IMAGE                 ("False")
	) ufm (
		.clock                   (ufm_clock_clk),          //    clk.clk
		.reset_n                 (ufm_reset_reset_n),      // nreset.reset_n
		.avmm_data_addr          (ufm_data_address),       //   data.address
		.avmm_data_read          (ufm_data_read),          //       .read
		.avmm_data_writedata     (ufm_data_writedata),     //       .writedata
		.avmm_data_write         (ufm_data_write),         //       .write
		.avmm_data_readdata      (ufm_data_readdata),      //       .readdata
		.avmm_data_waitrequest   (ufm_data_waitrequest),   //       .waitrequest
		.avmm_data_readdatavalid (ufm_data_readdatavalid), //       .readdatavalid
		.avmm_data_burstcount    (ufm_data_burstcount),    //       .burstcount
		.avmm_csr_addr           (ufm_csr_address),        //    csr.address
		.avmm_csr_read           (ufm_csr_read),           //       .read
		.avmm_csr_writedata      (ufm_csr_writedata),      //       .writedata
		.avmm_csr_write          (ufm_csr_write),          //       .write
		.avmm_csr_readdata       (ufm_csr_readdata)        //       .readdata
	);

endmodule
